AWSTemplateFormatVersion: "2010-09-09"
Description: tests String macro functions
Parameters:
  InputString:
    Default: "This is a test input string"
    Type: String
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      Tags:
        - Key: Upper
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: Upper
        - Key: Lower
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: Lower
        - Key: Capitalize
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: Capitalize
        - Key: Title
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: Title
        - Key: Replace
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: Replace
                 Old: " "
                 New: "_"
        - Key: Strip
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: Strip
                 Chars: Tgif
        - Key: ShortenLeft
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: MaxLength
                 Length: 4
                 StripFrom: Left
        - Key: ShortenRight
          Value:
            'Fn::Transform':
               Name: 'String'
               Parameters:
                 InputString: !Ref InputString
                 Operation: MaxLength
                 Length: 4
