AWSTemplateFormatVersion: '2010-09-09'
Description: 'StackSet administration role for management account'

Resources:
  AWSCloudFormationStackSetAdministrationRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Explicit role name required for StackSet service and cross-stack references in pipeline"
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource: 'arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole'

Outputs:
  AdministrationRoleArn:
    Description: ARN of the StackSet administration role
    Value: !GetAtt AWSCloudFormationStackSetAdministrationRole.Arn
    Export:
      Name: StackSetAdministrationRoleArn